### ISSUE TITLE
Fails on image found in the wild

### ISSUE THREAD

**Issue by Deebster** [noword/image2sgf#2]
Using the image from a [reddit post](https://old.reddit.com/r/baduk/comments/132db5c/were_beginners_what_was_the_score/) fails on step one and never completes step 2:
![r_baduk-132db5c-g6q60h265rwa1-img2sgf](https://user-images.githubusercontent.com/29483/235281271-9c4f6300-91f2-4d86-b5e9-15a2d3fe6acf.jpg)
(status bar should be showing "step 2: perspective correct the board, then classify stones")

I cropped the image:
![r_baduk-132db5c-g6q60h265rwa1-cropped](https://user-images.githubusercontent.com/29483/235281293-698a7f44-5fde-4cd8-8de8-45f15d1de80d.png)

And tried again:
![r_baduk-132db5c-g6q60h265rwa1-cropped-img2sgf](https://user-images.githubusercontent.com/29483/235281552-f6728053-2dd9-417d-a019-42facea6799f.jpg)

Apart from a few mistakes (that still leave a valid board), it appears to complete step 2, but then gives the error "Recognition failed" and the status bar reads "Error: Can't generate sgf."

**Comment by noword** [comment]
It's fixed.
Thank you.

https://github.com/noword/image2sgf/releases/tag/v0.07

**Comment by Deebster** [comment]
I can confirm that the cropped image now is error-free and exports to SGF. Speedy work, very impressive!
