### ISSUE TITLE
Can  the accuracy be improved by adjusting parameters? 

### ISSUE THREAD

**Issue by ebizmis** [noword/image2sgf#4]
A blank point was misidentified as a white stone.
<img width="1298" alt="reg1" src="https://github.com/noword/image2sgf/assets/30751149/7efbfbed-c2a0-481d-a7ff-40070391826b">

**Comment by noword** [comment]
Can you upload the left one original picture?

**Comment by ebizmis** [comment]
![5](https://github.com/noword/image2sgf/assets/30751149/35e2b480-a714-47fd-a051-5e0a3e5862af)
Thanks a lot!

**Comment by ebizmis** [comment]
[http://www.ebizmis.com/5.jpg](url)

**Comment by ebizmis** [comment]
Download original picture from here: http://www.ebizmis.com/5.jpg

**Comment by ebizmis** [comment]
Download original picture from here: http://www.ebizmis.com/6.jpg

**Comment by ebizmis** [comment]
sgf file: http://www.ebizmis.com/6.jpg.sgf

**Comment by ebizmis** [comment]
<img width="1298" alt="reg1" src="https://github.com/noword/image2sgf/assets/30751149/03aa5472-ba71-4f6e-8de2-15a7239bf63e">

**Comment by noword** [comment]
Please download the newest stone.pth at https://github.com/noword/image2sgf/releases/tag/v0.07
Then try again.

**Comment by ebizmis** [comment]
Yes, great!
