### ISSUE TITLE
one stone error

### ISSUE THREAD

**Issue by ebizmis** [noword/image2sgf#6]
download image [here](http://www.ebizmis.com/8.jpg)

Missing one white stone:
![8-after](https://github.com/noword/image2sgf/assets/30751149/9d208ca2-2cb8-473a-9275-a47edee9a14b)

**Comment by noword** [comment]
下载最新的stone.pth，再试试

https://github.com/noword/image2sgf/releases/edit/v0.07

**Comment by ebizmis** [comment]
好了，谢谢
