### ISSUE TITLE
发现一个很有趣的问题

### ISSUE THREAD

**Issue by ebizmis** [noword/image2sgf#7]
把一个棋谱照片quality-100.jpg，通过不同的压缩参数生成quality-30.jpg, quality-50.jpg, quality-60.jpg, quality-70.jpg, quality-80.jpg, quality-90.jpg。发现quality 70以上的可以正常转成相应的sgf，60及以下的都识别有错误的棋子，请noword研究一下如何在底quality下的jpg也可以被正确识别。

[下载](http://www.ebizmis.com/quality.zip)

**Comment by noword** [comment]
正常现象
