### ISSUE TITLE
can't find the imgs.py under /gui directory

### ISSUE THREAD

**Issue by linwenrui96** [noword/image2sgf#9]
Hi author of image2sgf,

This is very useful project. However, I'm looking for help to solve an issue when runing img2sgf.py.

>     from gui.main import *
>     import imgs
>     ModuleNotFoundError: No module named 'imgs'

I'm thinking there might be a imgs.py missing. Or do you have any idea why this is happening. I'm a newbie to python and would love help!

Bests,
Wendy

**Comment by noword** [comment]
https://github.com/noword/image2sgf/blob/master/img2sgf.py

没有你说的代码

**Comment by linwenrui96** [comment]
您好，是/gui/main.py 的第三行import imgs这里一直报错，所以我猜是需要一个imgs.py如果不是的话，您知道这个imgs package是哪里的subpackage么？谢谢你的回复Sent from Android deviceOn Mar 8, 2024 10:20, noword ***@***.***> wrote:
https://github.com/noword/image2sgf/blob/master/img2sgf.py
没有你说的代码

**Comment by noword** [comment]
执行pack_imgs.py，会生成imgs.py

**Comment by linwenrui96** [comment]
Thank you. This issue was solved by running pack_imgs.py.
